### ISSUE TITLE
xlunch does not work when I login from another user

### ISSUE THREAD

**Issue by josefelixrc7** [Tomas-M/xlunch#135]
xlunch works fine from my personal user, (**from which I installed xlunch**) but when *I log in from another user* and launch xlunch, it does not work or open. I open it from the terminal and it doesn't give any message. **I am on Arch Linux with Kernel 5.9.14**

Regards

**Comment by PMunch** [comment]
Have you had a look at the `--input` parameter? Xlunch defaults to read stdin if data is available there, otherwise it reads from `$HOME/.config/xlunch/entries.dsv` or `/etc/xlunch/entries.dsv` in that order. I'm guessing that the other users on your system have an empty `entries.dsv` file in `$HOME/.config/xlunch/entries.dsv` or that your user has `$HOME/.config/xlunch/entries.dsv` but `/etc/xlunch/entries.dsv` is empty.

**Comment by josefelixrc7** [comment]
I already managed to solve the problem using xlunch with the `--multiple` option
