### ISSUE TITLE
Bspwm - Launching through keybiding xlunch dont display apps icons

### ISSUE THREAD

**Issue by ghost** [Tomas-M/xlunch#44]
If I run xlunch through a terminal: icons appear 
> Icons: https://imgur.com/aYtjCnQ 

Through a key binding: RUN text is displayed but not apps icons
> No  icons: https://imgur.com/tV5KrgN 

KeyBiding:
>  https://imgur.com/FCvILTk 

` which: /usr/bin/xlunch`
`make install`

Arch Linux

**Comment by PMunch** [comment]
Xlunch will try to find the entries file in your system, specifically under `/etc/xlunch/entries.dsv` and `~/.config/xlunch/entries.dsv`. It seems like it is unable to find any of the files, or don't have permission to open them. You can try running xlunch with `--input <entries file>` in order to tell it to look for a file explicitly. But running xlunch from a keyboard shortcut works fine for me in i3, so I'm not sure what prompts this behaviour from bspwm.

**Comment by PMunch** [comment]
@oldgaro did you resolve this?

**Comment by ghost** [comment]
Oh, my bad!

It worked fine. haha

**Comment by PMunch** [comment]
Good to hear that it worked! Closing this issue now :)
