### ISSUE TITLE
Icon padding should not push out text

### ISSUE THREAD

**Issue by Tomas-M** [Tomas-M/xlunch#49]
When I want more free space between apps, I use -I 50 for example.
Unfortunately this behaves more like an "icon margin", it adds margin around the icon, but does not count the text to it, so it shifts the text down, far far away from the image.

I would like to be able to specify margin between apps, and to specify spacing between icon and the text under it.

So in ideal situation, I would use --iconpadding 50 --textpadding 10, and I would expect this to put the text only 10 pixels below the icon, and make the icon(including text) 50px padding around.

Can this be achieved with current options?
If not, will you please change the behavior of --iconpadding, so it actually acts as "app margin" ?
Thanks

**Comment by Tomas-M** [comment]
Alternatively, add --margin which specifies free space between icons. Did I have this already implemented in my version 2?

**Comment by Tomas-M** [comment]
I finally had a chance to test the xlunch application thoroughly. And I am really sad. You removed my options for margin (-m) and padding (-p). Please add them back. I don't have time to fix this myself, so please be so kind and do that yourself. Without it, the entire application lacks very important feature since user is UNABLE to adjust the look.

Attached is ugly image illustrating what is margin, what is padding and what is spacing. Those MUST be configurable separately. This is a must have. I'll revert to version 2.4 if this is not properly implemented :( @PMunch, let me know please if you're going to do that. Thank you!

![screen](https://user-images.githubusercontent.com/2259370/32146912-ad0916ae-bcde-11e7-9994-0521c73deaac.png)

**Comment by PMunch** [comment]
Hmm, yes this was changed on purpose. Having margin doesn't really make any sense since it means that border+apps*(padding*2+img_width)+margin*(apps-1) doesn't need to be equal to screen_width-border. This would mean that there is a strange gap after the last column of icons before the border, making the right border look wider than the left. Instead I changed it to work with number of rows and columns instead, and have apps placed equidistantly on the screen so that all borders appear the same size. The default is to show as many applications as possible on the screen, to get some more space between icons simply lower the amount of rows and columns. [This](https://github.com/Tomas-M/xlunch/blob/master/docs/spacings.svg) image shows what all the other options controls.

As for padding vs. spacing I could change it so that iconpadding applies around the image and the bottom of the text. And textpadding applies on the text sides and the spacing between text and image. I can even add a switch to choose between how it is now and how it was before.

**Comment by Tomas-M** [comment]
I believe that what you described was not a problem in my code (version 2.4) since there was some calculation made to fix that by adjusting the left/right borders, if I remember correctly.

Anyway, I believe that the user absolutely must have the possibility to adjust the look. And I, as an user, cannot do that now, and I am sad about that :)

Your proposed solution will not provide sufficient customization. The problem is that your way only allows for setting padding, which is a space INSIDE the clickable icon area. So if you set big padding, like 200, the whole 200x200 square will be clickable (and highlighted on hover). I am missing a different feature - a feature to specify eg. padding like 20, so the hovered square is like 68x68 px, but bigger margin between the icons, like 30, so there is much more space between them. You can look at my original code's screenshots at xlunch.org, it is impossible to make it look as like on the screenshots now :(

I really appreciate your work because what you have done so far made the xlunch application much greater than it was before. Yet I am considering myself a project owner and I would like to have MY features implemented. And it is very hard for me to express myself now, while not acting like an asshole :-) english is not my native language and sometimes I  may sound a little bit bitchy :) sorry about that :) Is there any way you could make it work the way I want, please? :-)

**Comment by PMunch** [comment]
I think I remember having an issue with it, but I might be wrong.

You can adjust the margin between icons by setting how many rows and columns of icons you want with the `--columns` and `--rows` options. The below images shows how this affects the spacing.
![allicons](https://user-images.githubusercontent.com/2845482/32149570-d33d19f6-bd06-11e7-9c68-8521afd89e6c.png)
This is the default, just running it without setting anything on my machine (apart from telling it were to find it's icons).
![threebythree](https://user-images.githubusercontent.com/2845482/32149571-d3592506-bd06-11e7-8024-9f37023b9f3f.png)
Here I've set `--columns 3 --rows 3` telling xlunch I want 3x3 icons. Since it still uses the small default border it looks a bit strange but you get the point. In both images the clickable size is the same, but the spacing between them has changed. The icons are also placed right up against the borders on all sides. If you use `--windowed` to put it in windowed mode you can play around with resizing the window and see how xlunch is recalculating were to put the icons.

I totally understand that you want to have control over this project, after all it is _your_ project :) And don't worry, you're not coming across as an asshole, I can see your concern and I hope you will find the solution satisfactory. I implemented it this way because I think it makes more sense. I found playing around with margins vs. borders and having things resize without my will to be a bit confusing and I thought this would make it easier to customise.

![example](https://user-images.githubusercontent.com/2845482/32149847-15ce50d8-bd0b-11e7-8d01-cfcd361ec8e1.png)
For fun I decided to try and make it look as similar to the screenshot as possible. It's not perfect, but if I add the option to have have the iconpadding on the bottom below the text instead I think it will be almost exactly the same.

**Comment by PMunch** [comment]
Okay, added an option `-X, --paddingswap` which switches the order of icon padding and text padding around text. With this enabled the order is `icon padding -> icon -> text padding -> text -> icon padding`. This applies to both normal and `--textafter` mode. With this option enabled the screenshots looks almost exactly the same.

**Comment by Tomas-M** [comment]
Thank you very much for the new option -X. I would really prefer if this was the default
It is almost what I want, but still there is the lack for user configuration for space between icons. If user wants small icons, small hover box around them, but big gap between the icons, he cannot make it, since currently xlunch forces the user to have huge hover box.

Regarding the margins, my concern is following: I do not know beforehand how big is the screen. I want to run xlunch in Slax, which runs on many different computers with different screens. Each user has different screen width. Thus I cannot hardcode --columns to specify how many columns there should be, because different screen widths would mean different amount of empty columns in order for me to get three left-aligned icons with sime reasonable empty space between them. (as you can see using make test).

Currently xlunch puts some empty space between the icons. (see screenshot). I am not sure how you calculate it, or where it is set, but could it work in a way that you add a parameter where user can specify that particular spacing as a margin? Since you already have some spacing there, just make it configurable, and if it cannot be set as fixed size, let user set it as a 'hint' for further calculations, while it can be slightly recalculated if xlunch needs. Thank you

![image](https://user-images.githubusercontent.com/2259370/32159005-c3a694aa-bd4b-11e7-8d1c-22da7f195e55.png)

**Comment by PMunch** [comment]
The space currently there is just whatever is left after all the space has been used for applications. So if you have room for 5.5 columns then it will give you 5 columns and use the remaining 0.5 space as margin between icons.

Hmm, to be honest I didn't consider running the same configuration on many different machines without any changes. I assumed that people would configure it to their liking on their own system. I use it in two scenarios like that however. In my home setup I have a vertical and two horizontal monitors, and at work I have a laptop with a small screen docked to a larger screen. The way I've dealt with this is to simply have a bash script that sees which screen I am on and calculates the amount of columns based on that. I would for example do something like this: `xlunch --columns $(i3-msg -t get_workspaces | jq -r "map(select(.focused))[0].rect.width" | echo "(($(cat -)-192*2)/(48+20))/2" | bc)`.

I could of course add an option for margin which would be added to the calculation of the size of a row/column when figuring out how many items to place on screen. It won't be an exact thing as it would still fit as many as it could and then use the remaining space for margins, but it would act as a minimum. So the margin between items would be in the range `[margin, margin+app_size>`

**Comment by Tomas-M** [comment]
What you suggested is a great idea, but only if xlunch does that itself, no need for any external programs.

If user specifies margin, lets just calculate --columns for him based on the margin and other parameters known in xlunch. If user specifies --columns, lets just ignore margin.

If the empty space is in the range [margin, margin+app_size> that is perfectly fine.

**Comment by Tomas-M** [comment]
The same for --rows

**Comment by Tomas-M** [comment]
By the way, the interval with margin will be [margin, margin+app_size/columns> or something like that, because the remainter splits between all columns, so the "error" in margin size will be hardly noticable, and I will be prefectly happy with that.

**Comment by PMunch** [comment]
Ah, I guess you're right when it comes to the math. My bad. Added an option `-l, --leastmargin` now which I think does what you want, it adds the margin to the minimum size an application icon must have.

EDIT: I managed to push the wrong branch. So sorry. I'll fix it right away

**Comment by Tomas-M** [comment]
Awesome, thank you million times, this is what I want !
Just the lowercase L looks like number one 1, so lets hope users won't be confused :] they shouldn't since the leastmargin description is right next to it... but you never know :)

**Comment by PMunch** [comment]
Yeah, lowercase l isn't the best identifier. But we're running out of letters with all these options :P I think we actually only miss 4-5 to have all lowercase letters do something.
