### ISSUE TITLE
Tag 3.1.2 shows 3.1.1 as version

### ISSUE THREAD

**Issue by PMunch** [Tomas-M/xlunch#62]
Seems like you forgot to update the version in the file and docs before applying a new tag.

**Comment by Tomas-M** [comment]
Yeah, I've made that version only for my purposes, I needed to remove your last commit to keep my --center behavior since I'm releasing Slax in few days and I need xlunch to center things. I'm not sure if you will have time to implement the --border auto today so I did this to make sure my build scripts are downloading proper version (before your last commit).

Once the --border auto is there, or something else which makes it center, we can release 3.1.3 properly. Don't have much time now, pressure on me :)

**Comment by Tomas-M** [comment]
Closing with WONTFIX :)

**Comment by PMunch** [comment]
I see, I hope to have it done today.
