### ISSUE TITLE
Winkey Keyboard Shortcut for Application Menu?

### ISSUE THREAD

**Issue by adnan360** [Tomas-M/xlunch#71]
I love the new Slax 9. Although it is new and it has some things to be a bit tedious to setup (for example, showing icons, changing icon size etc.) but it is very lightweight and fast. I am sure it will grow to be more feature-rich over time.

I was wondering, can I get the Win Key/Meta key as a shortcut? If so, can we get this as a default in the next version? As much as I remember, previous version had this by default with KDE.

Thanks for such a low size distro and switching to debian.
Thanks for your hard work.
All the best to xlunch.

**Comment by Tomas-M** [comment]
I am not sure if this request is xlunch-related or slax-related.
Win key shortcut, what for? To start xlunch in Slax, I suppose? Then it is Slax related so I'm closing this, since these issues here are for xlunch, not for Slax, sorry :)

I am afraid that fluxbox cannot exec commands on pure Mod4 keypress, it needs a combination of Mod4 plus something.
