### ISSUE TITLE
Translating

### ISSUE THREAD

**Issue by alexandre-mbm** [Tomas-M/xlunch#74]

**Comment by Tomas-M** [comment]
Slax does not support translations, I am sorry

**Comment by PMunch** [comment]
You could easily translate xlunch though by using --prompt and make sure the entries use your language. PRs welcome to include a language option to genentries so that it will pick the right name for your language!

**Comment by alexandre-mbm** [comment]
@PMunch, where is the call to XLunch on Slax? It looks like it is named RootMenu...

**Comment by Tomas-M** [comment]
Ah, I was replying dozens of Slax-related issues in another repo and I didn't notice that this issue is in xlunch repository.

Basically, xlunch does not need to be translated, since all the output can be controlled by the user.

To answer the last question, xlunch calls in Slax are in /usr/bin/fbappselect script, and /usr/bin/fblogout script. @alexandre-mbm please stop asking Slax-related questions in xlunch github. Thanks for understanding.

**Comment by alexandre-mbm** [comment]
> To answer the last question, xlunch calls in Slax are in /usr/bin/fbappselect script, and /usr/bin/fblogout script.

Thanks. I will see it.

> @alexandre-mbm please stop asking Slax-related questions in xlunch github. Thanks for understanding.

Here was about xlunch...

**Comment by alexandre-mbm** [comment]
Now I see that I can translate the below files:

- /etc/xlunch/entries.dsv
- /etc/xlunch/logout.dsv

Sorry and thanks!
