### ISSUE TITLE
Background blur maybe?

### ISSUE THREAD

**Issue by nejdetckenobi** [Tomas-M/xlunch#83]
It might be nice to support background blur like in OSX. 
I don't know if the appearance effect can be controlled via xlunch but fade-in/fade-out option would be useful while using the blur effect on launcher start.

**Comment by Tomas-M** [comment]
This works already, you just need to have a compositor for X11 running.
Like compton, xcompmgr or such.

**Comment by PMunch** [comment]
To expand this answer, if you are using compton and would like to have only xlunch blurred you can add something like this to your config:
```
blur-kern = "3x3box";
blur-background-exclude = [ "!class_g = 'xlunch'" ];
blur-background = true;
```
This will blur all windows, excluding those that are not xlunch ie. only xlunch windows. Make sure that your computer is set up to use the graphics card though when you do this. Otherwise you'll get abysmal performance.

**Comment by nejdetckenobi** [comment]
Thanks a lot!

**Comment by PMunch** [comment]
No problem 😃 If you create something nice I'd love to see a screenshot
